# -*- coding: utf-8 -*-

from django.conf import settings

CLIENTSIGNAL_MULTIPLEXED_CONNECTION_DEFAULT = 'clientsignal.SignalConnection'
CLIENTSIGNAL_BASE_SIGNALCONNECTION_DEFAULT = 'clientsignal.SignalConnection'

CLIENTSIGNAL_MULTIPLEXED_CONNECTION = getattr(settings, 
        'CLIENTSIGNAL_MULTIPLEXED_CONNECTION',
        CLIENTSIGNAL_MULTIPLEXED_CONNECTION_DEFAULT)
CLIENTSIGNAL_BASE_SIGNALCONNECTION = getattr(settings, 
        'CLIENTSIGNAL_BASE_SIGNALCONNECTION',
        CLIENTSIGNAL_BASE_SIGNALCONNECTION_DEFAULT)


